[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://expalapp.netlify.app"
  NEXT_PUBLIC_APP_URL = "https://expalapp.netlify.app"
  NEXT_PUBLIC_APP_ID = "com.yourbrandexpal"

[[plugins]]
  package = "@netlify/plugin-nextjs"
